# This is the configuration file for deploying the React frontend to Netlify.

[build]
  # This is the command Netlify will run to build your site for production.
  # It's the standard command for Create React App.
  command = "npm run build"
  
  # This is the directory that contains the final, built static files.
  # Create React App outputs to a folder named "build".
  publish = "build"
  
  # This is the directory where Netlify will run the build command.
  # Since this file is in the `frontend` directory, we can use "." for the current directory.
  base = "."

[[redirects]]
  # This is the crucial rule for Single Page Applications (SPAs) like React.
  # It tells Netlify that for any path that doesn't match a specific file,
  # it should serve the `index.html` file and let React Router handle the routing.
  # This is what makes deep links (e.g., /dashboard/wallets) work correctly.
  from = "/*"
  to = "/index.html"
  status = 200
