# FILE: frontend/netlify.toml

# This sets the build command and the directory where the final site is located.
# The `base` directory tells Netlify to run the build command from within the 'frontend' folder.
[build]
  command = "npm run build"
  publish = "frontend/build" # Correct path to the output directory
  base = "" # Run npm install and build from the root of the repo

# [THE DEFINITIVE, FINAL FIX FOR CHUNKLOADERROR & SYNTAX]

# Rule 1: For all static assets (JS, CSS chunks) inside the /static directory.
# Because their filenames have a unique hash, they can be cached "forever" by the browser.
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Rule 2: For all other paths, specifically the main index.html file.
# This is the catch-all for your React Router paths.
# It tells the browser it can cache the file, but it MUST re-check with the
# server on every visit to see if there's a new version. This prevents stale deployments.
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# This redirect rule is crucial for Single-Page Applications (SPA) like React.
# It ensures that if a user directly visits or refreshes a page like /dashboard/developer,
# Netlify serves the main index.html file, allowing React Router to handle the routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
