# FILE: netlify.toml (at the VERY ROOT of your repository)

[build]
  # Base directory: Where your frontend code lives.
  base = "frontend"

  # Build command: To be run inside the 'base' directory.
  command = "npm run build"

  # Publish directory: The folder to deploy, relative to the 'base' directory.
  # Since the `build` folder is created inside `frontend`, this is the correct path.
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
